image: gcc:latest

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake git
  script:
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/

test:
  stage: test
  script:
    - cd build/
    - ctect
