image: gcc:latest

stages:
  - build
  - unit_test
  - acceptance_test

build:
  stage: build
  before_script:
    - apt update && apt -y install cmake git
  script:
    - cmake -S . -B build
    - cmake --build build
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/

unit_test:
  stage: unit_test
  script:
    - cd build/
    - ctest -R unit

acceptance_test:
  stage: acceptance_test
  script:
    - cd build/
    - ctest -R accept
