name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc g++ cmake git

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --parallel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  unit_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run unit tests
        run: |
          cd build
          chmod +x test/unit_test
          ctest -R unit --output-on-failure

  acceptance_test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Run acceptance tests
        run: |
          cd build
          chmod +x test/acceptance_test
          ctest -R accept --output-on-failure
