name: C++ CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y clang-format clang-tidy cmake clang

      - name: clang-format check (lib)
        run: |
          FILES=$(find lib -name "*.cpp" -o -name "*.hpp" -o -name "*.h")
          clang-format -style=file -i $FILES
          git diff --exit-code

      - name: Run clang-tidy (lib)
        run: |
          FILES=$(find lib  -name "*.cpp" -o -name "*.hpp" -o -name "*.h")
          for f in $FILES; do
            clang-tidy "$f" -warnings-as-errors=* -- -Ilib/include -std=c++20 -x c++
          done

  gcc_build_lib:
    runs-on: ubuntu-latest
    needs: lint_lib

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC
        run: |
          sudo apt update
          sudo apt install -y gcc g++ cmake

      - name: Configure
        run: |
          cmake -S lib -B build-lib-gcc \
          -DCMAKE_CXX_COMPILER=g++ \
          -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build-lib-gcc --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: build-lib-gcc
          path: build-lib-gcc/

  clang_build_lib:
    runs-on: ubuntu-latest
    needs: lint_lib

    steps:
      - uses: actions/checkout@v4

      - name: Install clang
        run: |
          sudo apt update
          sudo apt install -y clang cmake

      - name: Configure
        run: cmake -S lib -B build-lib-clang -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build-lib-clang --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: build-lib-clang
          path: build-lib-clang/

  unit_test_lib:
    runs-on: ubuntu-latest
    needs: gcc_build_lib

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-lib-gcc
          path: build

      - name: Configure tests
        run: |
          cmake -S test -B build-test \
            -DCMAKE_CXX_FLAGS="-I$PWD/lib/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$PWD/build \
              -Wl,-rpath,$PWD/build" \
            -DENABLE_COVERAGE=ON

      - name: Build tests
        run: cmake --build build-test --parallel

      - name: Run lib unit tests
        run: |
          cd build-test
          chmod +x lib_unit_test
          ctest -R lib_unit_test --output-on-failure

  lint_app:
    runs-on: ubuntu-latest
    needs: unit_test_lib
    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y clang-format clang-tidy cmake clang

      - name: clang-format check (app)
        run: |
          FILES=$(find app -name "*.cpp" -o -name "*.hpp" -o -name "*.h")
          clang-format -style=file -i $FILES
          git diff --exit-code

      - name: Run clang-tidy (app)
        run: |
          FILES=$(find app  -name "*.cpp" -o -name "*.hpp" -o -name "*.h")
          for f in $FILES; do
            clang-tidy "$f" -warnings-as-errors=* -- -Ilib/include -std=c++20 -x c++
          done

  gcc_build_app:
    runs-on: ubuntu-latest
    needs: [lint_app, gcc_build_lib]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-lib-gcc
          path: build

      - name: Install GCC
        run: |
          sudo apt update
          sudo apt install -y gcc g++ cmake

      - name: Configure
        run: |
          cmake -S app -B build-app-gcc \
            -DCMAKE_CXX_FLAGS="-I$PWD/lib/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$PWD/build \
              -Wl,-rpath,$PWD/build" \
            -DCMAKE_CXX_COMPILER=g++ \
            -DENABLE_COVERAGE=ON

      - name: Build
        run: cmake --build build-app-gcc --parallel

      - uses: actions/upload-artifact@v4
        with:
          name: build-app-gcc
          path: build-app-gcc/

  clang_build_app:
    runs-on: ubuntu-latest
    needs: [lint_app, clang_build_lib]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-lib-clang
          path: build

      - name: Install clang
        run: |
          sudo apt update
          sudo apt install -y clang cmake

      - name: Configure
        run: |
          cmake -S app -B build-app-clang \
            -DCMAKE_CXX_FLAGS="-I$PWD/lib/include" \
            -DCMAKE_EXE_LINKER_FLAGS="-L$PWD/build \
              -Wl,-rpath,$PWD/build" \
            -DCMAKE_CXX_COMPILER=clang++

      - name: Build
        run: cmake --build build-app-clang --parallel

  unit_test_app:
    runs-on: ubuntu-latest
    needs: gcc_build_app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-app-gcc
          path: build-app

      - uses: actions/download-artifact@v4
        with:
          name: build-lib-gcc
          path: build-lib

      - name: Configure tests
        run: |
          cmake -S test -B build-test \
            -DCMAKE_CXX_FLAGS="-I$PWD/lib/include -I$PWD/app" \
            -DCMAKE_EXE_LINKER_FLAGS="\
              -L$PWD/build-lib \
              -L$PWD/build-app \
              -Wl,-rpath,$PWD/build-lib:$PWD/build-app" \
            -DENABLE_COVERAGE=ON

      - name: Build tests
        run: cmake --build build-test --parallel

      - name: Run app unit tests
        run: |
          cd build-test
          chmod +x app_unit_test
          ctest -R app_unit_test --output-on-failure

      - uses: actions/upload-artifact@v4
        with:
          name: build-test
          path: build-test/

  coverage:
    runs-on: ubuntu-latest
    needs: unit_test_app

    steps:
      - uses: actions/checkout@v4

      - name: Install gcovr
        run: python3 -m pip install gcovr

      - uses: actions/download-artifact@v4
        with:
          name: build-lib-gcc
          path: build-lib-gcc

      - uses: actions/download-artifact@v4
        with:
          name: build-app-gcc
          path: build-app-gcc

      - name: Download coverage data
        uses: actions/download-artifact@v4
        with:
          name: build-test
          path: build-test

      - name: Generate coverage reports
        run: |
          gcovr -r $GITHUB_WORKSPACE \
                build-test \
                build-lib-gcc \
                build-app-gcc \
                --xml coverage.xml \
                --html-details coverage.html \
                --print-summary

      - name: Upload coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html

      - name: Create coverage summary + badge
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: both
          hide_complexity: true

      - name: Upload badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badge
          path: code-coverage-badges

  acceptance_test:
    runs-on: ubuntu-latest
    needs: [gcc_build_app, unit_test_app, unit_test_lib]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-test
          path: build-test

      - name: Run acceptance tests
        run: |
          cd build-test
          chmod +x acceptance_test
          ctest -R acceptance_test --output-on-failure
